from pathlib import Path

p=Path('app/src/main/java/ru/zvonilka/prototype/PhoneService.kt')
s=p.read_text()
old='''        if (Build.VERSION.SDK_INT >= 31) {\n            val person = Person.Builder().setName(displayName).setImportant(true).build()\n            builder.setStyle(if (ringing) Notification.CallStyle.forIncomingCall(person, action("reject"), action("answer"))\n                else Notification.CallStyle.forOngoingCall(person, action("hangup")))\n        } else {\n            if (ringing) builder.addAction(Notification.Action.Builder(null, "Принять", action("answer")).build())\n            builder.addAction(Notification.Action.Builder(null, if (ringing) "Отклонить" else "Завершить", action(if (ringing) "reject" else "hangup")).build())\n        }\n        if (Build.VERSION.SDK_INT < 33 || checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS) == android.content.pm.PackageManager.PERMISSION_GRANTED) {\n            manager.notify(id, builder.build())\n        }'''
new='''        // Samsung Android 16 (API 36) rejects our CallStyle payload at NotificationManager\n        // with IllegalArgumentException. Use a standard CATEGORY_CALL notification on API 36+\n        // while keeping the same actions and full-screen intent.\n        if (Build.VERSION.SDK_INT in 31..35) {\n            val person = Person.Builder().setName(displayName).setImportant(true).build()\n            builder.setStyle(if (ringing) Notification.CallStyle.forIncomingCall(person, action("reject"), action("answer"))\n                else Notification.CallStyle.forOngoingCall(person, action("hangup")))\n        } else {\n            if (ringing) builder.addAction(Notification.Action.Builder(null, "Принять", action("answer")).build())\n            builder.addAction(Notification.Action.Builder(null, if (ringing) "Отклонить" else "Завершить", action(if (ringing) "reject" else "hangup")).build())\n        }\n        if (Build.VERSION.SDK_INT < 33 || checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS) == android.content.pm.PackageManager.PERMISSION_GRANTED) {\n            try {\n                manager.notify(id, builder.build())\n            } catch (error: IllegalArgumentException) {\n                CallDiagnostics.record(this, "notification_primary_rejected", error)\n                val fallback = Notification.Builder(this, if (ringing) "calls" else "ongoing")\n                    .setSmallIcon(android.R.drawable.sym_action_call)\n                    .setContentTitle(displayName)\n                    .setContentText(CallStore.state(call))\n                    .setCategory(Notification.CATEGORY_CALL)\n                    .setOngoing(true)\n                    .setOnlyAlertOnce(true)\n                    .setVisibility(Notification.VISIBILITY_PRIVATE)\n                    .setContentIntent(open)\n                if (ringing) {\n                    fallback.setFullScreenIntent(open,true)\n                    fallback.addAction(Notification.Action.Builder(null,"Принять",action("answer")).build())\n                }\n                fallback.addAction(Notification.Action.Builder(null,if(ringing) "Отклонить" else "Завершить",action(if(ringing) "reject" else "hangup")).build())\n                manager.notify(id,fallback.build())\n            }\n        }'''
if old not in s:
    raise SystemExit('PhoneService notification block not found')
s=s.replace(old,new,1)
p.write_text(s)

p=Path('app/build.gradle.kts')
s=p.read_text().replace('versionCode = 31','versionCode = 32').replace('versionName = "0.12.3"','versionName = "0.12.4"')
p.write_text(s)
