from pathlib import Path

p=Path('app/src/main/java/ru/zvonilka/prototype/MainActivity.kt')
s=p.read_text()
old='''            bottomBar={ if(!settings && selected==null) NavigationBar(containerColor=MaterialTheme.colorScheme.surface,tonalElevation=0.dp) {\n                listOf(Icons.Outlined.History,Icons.Outlined.Contacts,Icons.Outlined.Dialpad).forEachIndexed { i,icon->\n                    NavigationBarItem(\n                        colors=NavigationBarItemDefaults.colors(indicatorColor=MaterialTheme.colorScheme.primaryContainer.copy(alpha=.55f),selectedIconColor=MaterialTheme.colorScheme.primary,selectedTextColor=MaterialTheme.colorScheme.primary),\n                        selected=tab==i,onClick={tab=i;if(i==0) MissedCalls.clear(this@MainActivity)},\n                        icon={BadgedBox(badge={if(i==0 && missedCount>0)Badge{Text(if(missedCount>99)"99+" else missedCount.toString())}}){Icon(icon,null,Modifier.size(22.dp))}},\n                        label={Text(listOf("Недавние","Контакты","Клавиши")[i],fontSize=10.sp,fontWeight=FontWeight.Normal)}\n                    )\n                }\n            } }\n'''
new='''            bottomBar={ if(!settings && selected==null) GlassBottomBar() }\n'''
if old not in s:
    raise SystemExit('bottom navigation block not found')
s=s.replace(old,new,1)
anchor='''    @Composable private fun SimBadge(p:PersonRecord) {\n'''
bar='''    @Composable private fun GlassBottomBar() {\n        val dark=isSystemInDarkTheme()\n        val labels=listOf("Недавние","Контакты","Клавиши")\n        val icons=listOf(Icons.Outlined.History,Icons.Outlined.Contacts,Icons.Outlined.Dialpad)\n        Box(\n            Modifier.fillMaxWidth().background(Color.Transparent).navigationBarsPadding().padding(horizontal=12.dp,vertical=8.dp),\n            contentAlignment=Alignment.Center\n        ) {\n            Surface(\n                modifier=Modifier.fillMaxWidth().height(70.dp),\n                shape=RoundedCornerShape(30.dp),\n                color=if(dark) MaterialTheme.colorScheme.surface.copy(alpha=.82f) else Color.White.copy(alpha=.84f),\n                border=BorderStroke(1.dp,if(dark) Color.White.copy(alpha=.12f) else Color.White.copy(alpha=.90f)),\n                shadowElevation=10.dp,\n                tonalElevation=0.dp\n            ) {\n                Row(Modifier.fillMaxSize().padding(5.dp),verticalAlignment=Alignment.CenterVertically) {\n                    icons.forEachIndexed { i,icon->\n                        val active=tab==i\n                        Box(\n                            Modifier.weight(1f).fillMaxHeight().clip(RoundedCornerShape(24.dp)).background(\n                                if(active) MaterialTheme.colorScheme.primaryContainer.copy(alpha=if(dark).62f else .70f) else Color.Transparent\n                            ).clickable {\n                                tab=i\n                                if(i==0) MissedCalls.clear(this@MainActivity)\n                            },\n                            contentAlignment=Alignment.Center\n                        ) {\n                            Column(horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center) {\n                                BadgedBox(badge={if(i==0 && missedCount>0) Badge { Text(if(missedCount>99)"99+" else missedCount.toString()) }}) {\n                                    Icon(\n                                        icon,labels[i],Modifier.size(if(active)23.dp else 22.dp),\n                                        tint=if(active) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha=.82f)\n                                    )\n                                }\n                                Spacer(Modifier.height(3.dp))\n                                Text(\n                                    labels[i],fontSize=10.sp,\n                                    fontWeight=if(active) FontWeight.SemiBold else FontWeight.Normal,\n                                    color=if(active) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha=.82f)\n                                )\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n\n'''
if anchor not in s:
    raise SystemExit('SimBadge anchor not found')
s=s.replace(anchor,bar+anchor,1)
p.write_text(s)

p=Path('app/build.gradle.kts')
s=p.read_text().replace('versionCode = 25','versionCode = 26').replace('versionName = "0.11.7"','versionName = "0.11.8"')
p.write_text(s)
